flags = ["--gpu-kernel-outlining", "--canonicalize"]
follows = [
  "https://mlir.llvm.org/docs/Dialects/GPU/#gpulaunch-gpulaunchop",
  "https://mlir.llvm.org/docs/Dialects/GPU/#gpulaunch_func-gpulaunchfuncop",
  "https://mlir.llvm.org/docs/Passes/#-gpu-kernel-outlining",
]
