#!/usr/bin/env python3
"""Generate the docs "memory system" from tools/docs/concepts/concepts.yml.

Every output lands under includes/ (repo root) and is pulled into pages with
pymdownx.snippets:

  abbreviations.md          hover tooltips (snippets auto_append + abbr)
  remember/<page-key>.md    "Before you start, remember" box, one per nav page
  next/<page-key>.md        "You will use this again in" list plus a local
                             concept-map box, one per nav page
  review/<group>.md         mixed recall-question banks
  concept-map.mmd           Mermaid flowchart of every `requires` edge
  concept-map-<book>.mmd    one flowchart per book (tour, spec, guide, backend,
                             optimize, gpu, mlir; other if any concept is left)

A page with nothing to show still gets an empty remember/next file, so every
page can include both unconditionally. page-key is the page path under docs/
without ".md", with "/" replaced by "__".

Usage:
  python tools/docs/concepts.py              write the outputs
  python tools/docs/concepts.py --check      exit 1 if any output is stale (CI)
  python tools/docs/concepts.py --scan       suggest used_in lists from docs text
  python tools/docs/concepts.py --self-test  run the built-in checks

main() returns 0 when everything is fine, 1 when --check finds stale files and
2 when concepts.yml fails validation.
"""

import argparse
import hashlib
import math
import posixpath
import re
import sys
from collections import Counter
from pathlib import Path

import yaml
from markdown.extensions.toc import slugify  # the slug the site's toc uses

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
DATA = ROOT / "tools" / "docs" / "concepts" / "concepts.yml"
OUT = ROOT / "includes"
NOTICE = "Generated by tools/docs/concepts.py from tools/docs/concepts/concepts.yml; do not edit."
GLOSSARY = "specification/glossary.md"

# Pages that list or summarise every term: a mention there is not a later use.
NOT_USERS = {
    "index.md",
    GLOSSARY,
    "language-and-compiler-cheatsheet.md",
    "compiler/guide/words.md",
    "compiler/guide/reading-list.md",
}
BOOKS = {"language-tour/": "tour", "specification/": "spec", "compiler/guide/": "guide",
         "backend/": "backend", "optimize/": "optimize", "gpu/": "gpu", "mlir/": "mlir"}
BOOK_TITLES = {"tour": "Language tour", "spec": "Specification", "guide": "Compiler guide", "backend": "Back end",
               "optimize": "Optimize", "gpu": "GPU", "mlir": "MLIR", "other": "Other pages"}

FIELDS = {
    "id", "term", "abbr", "aliases", "tooltip", "short", "definition", "spec",
    "spec_ref", "introduced_in", "requires", "used_in", "recall_question", "recall_answer",
}
REQUIRED = ("id", "term", "short", "definition", "introduced_in", "recall_question", "recall_answer")
SHORT_MAX, ANSWER_MAX = 110, 320
REMEMBER_MIN, REMEMBER_MAX, NEXT_MAX, NEXT_TERMS, USED_IN_MAX = 3, 5, 6, 4, 8
LOCAL_MAP_MAX = 12  # cap on nodes in a page's "Concept map for this page" box


# ---- inputs -------------------------------------------------------------------


def load_nav():
    """Return the nav pages in order as dicts with path, title and section."""

    class Loader(yaml.SafeLoader):
        pass

    # mkdocs.yml contains !!python/name tags; they do not matter here.
    Loader.add_multi_constructor("", lambda loader, suffix, node: None)
    config = yaml.load((ROOT / "mkdocs.yml").read_text(encoding="utf-8"), Loader=Loader)
    pages = []

    def walk(items, section):
        for item in items:
            title, value = (None, item) if isinstance(item, str) else next(iter(item.items()))
            if isinstance(value, list):
                walk(value, title)
            elif not value.startswith(("http://", "https://")):
                pages.append({"path": value, "title": title or first_heading(value), "section": section})

    walk(config["nav"], "")
    return pages


def first_heading(page):
    match = re.search(r"^# (.+)$", (DOCS / page).read_text(encoding="utf-8"), re.M)
    return match.group(1).strip() if match else page


def load_data():
    data = yaml.safe_load(DATA.read_text(encoding="utf-8"))
    for concept in data["concepts"]:
        concept.setdefault("aliases", [])
        concept.setdefault("requires", [])
        concept.setdefault("used_in", [])
    return data


def glossary_definitions():
    """Map each specification glossary term to its definition, whitespace-normalised."""
    text = (DOCS / GLOSSARY).read_text(encoding="utf-8")
    terms = text.split("## Terms", 1)[1].split("\n## ", 1)[0]
    return {term: " ".join(body.split()) for term, body in re.findall(r"^(\S.*)\n: (.*(?:\n  .*)*)", terms, re.M)}


def heading_slugs(page):
    """Anchors the toc extension creates for a page's headings (fenced code skipped)."""
    text = strip_fences((DOCS / page).read_text(encoding="utf-8"))
    slugs = set()
    for heading in re.findall(r"^#{1,6}\s+(.+?)\s*#*$", text, re.M):
        explicit = re.search(r"\{:?\s*#([\w.-]+)[^}]*\}$", heading)  # attr_list id
        if explicit:
            slugs.add(explicit.group(1))
            continue
        heading = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", heading).replace("`", "")
        slugs.add(slugify(heading, "-"))
    return slugs


def strip_fences(text):
    return re.sub(r"^[ \t]*(```|~~~)[^\n]*\n.*?^[ \t]*\1[^\n]*$", "", text, flags=re.S | re.M)


# ---- small pure helpers (covered by the self-test) ---------------------------


def page_key(page):
    return page[: -len(".md")].replace("/", "__")


def relative_link(target, host):
    """Link from the page `host` to `target` (both docs-relative, target may carry #anchor)."""
    path, _, anchor = target.partition("#")
    link = posixpath.relpath(path, posixpath.dirname(host) or ".")
    return f"{link}#{anchor}" if anchor else link


def tooltips_on(concept):
    """Tooltip rule: on by default only for concepts with an abbr; multi-word terms opt in."""
    return concept.get("tooltip", bool(concept.get("abbr")))


def tooltip_keys(concept):
    """Return {text to mark: tooltip} for one concept.

    abbr marks every exact, case-sensitive occurrence site-wide, so only the
    abbreviation and multi-word names are marked, never a single word. Plural
    and capitalised forms are left out on purpose: every extra form slows the
    render of every page, and they matched only 6% of occurrences.
    """
    if not tooltips_on(concept):
        return {}
    names = [concept["term"], *concept["aliases"]]
    keys = {name: concept["short"] for name in names if len(name.split()) > 1}
    abbr = concept.get("abbr")
    if abbr:
        keys[abbr] = concept["short"] if abbr == concept["term"] else f"{concept['term']}: {concept['short']}"
    return keys


# ---- validation ---------------------------------------------------------------


def validate(data, nav):
    """Return a list of human-readable problems (empty when the data is sound)."""
    errors = []
    order = {page["path"]: i for i, page in enumerate(nav)}
    concepts = data["concepts"]
    ids = [c.get("id") for c in concepts]
    by_id = {c.get("id"): c for c in concepts}
    for cid, count in Counter(ids).items():
        if count > 1:
            errors.append(f"{cid}: duplicate id")

    def check_page(where, page, allow_anchor=False):
        path, _, anchor = page.partition("#")
        if anchor and not allow_anchor:
            errors.append(f"{where}: {page} must not have an anchor")
        if path not in order:
            errors.append(f"{where}: {path} is not a page in the mkdocs.yml nav")
            return None
        if anchor and anchor not in heading_slugs(path):
            errors.append(f"{where}: {path} has no heading with anchor #{anchor}")
        return order.get(path)

    tooltip_owner = {}
    for c in concepts:
        cid = c.get("id", "?")
        errors += [f"{cid}: unknown field {key!r}" for key in sorted(set(c) - FIELDS)]
        missing = [key for key in REQUIRED if not c.get(key)]
        if missing:
            errors.append(f"{cid}: missing {', '.join(missing)}")
            continue
        if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", cid):
            errors.append(f"{cid}: id must be kebab-case")
        if len(c["short"]) > SHORT_MAX or re.search(r"[`*\[\]\n]", c["short"]):
            errors.append(f"{cid}: short must be plain text of at most {SHORT_MAX} characters")
        if '"' in c["recall_question"] or not c["recall_question"].endswith("?"):
            errors.append(f"{cid}: recall_question must end with ? and contain no double quote")
        if len(c["recall_answer"]) > ANSWER_MAX:
            errors.append(f"{cid}: recall_answer is longer than {ANSWER_MAX} characters")
        here = check_page(f"{cid}.introduced_in", c["introduced_in"])
        if c.get("spec_ref"):
            check_page(f"{cid}.spec_ref", c["spec_ref"], allow_anchor=True)
        for page in c["used_in"]:
            later = check_page(f"{cid}.used_in", page)
            if here is not None and later is not None and later <= here:
                errors.append(f"{cid}.used_in: {page} comes before {c['introduced_in']} in the nav")
        for rid in c["requires"]:
            other = by_id.get(rid)
            if other is None or rid == cid:
                errors.append(f"{cid}.requires: unknown or self reference {rid!r}")
            elif here is not None and order.get(other["introduced_in"], math.inf) > here:
                errors.append(f"{cid}.requires: {rid} is introduced after {cid} ({other['introduced_in']})")
        if tooltips_on(c) and not c.get("abbr") and len(c["term"].split()) < 2:
            errors.append(f"{cid}: tooltips are only for abbreviations and multi-word terms")
        for key in tooltip_keys(c):
            if tooltip_owner.setdefault(key, cid) != cid:
                errors.append(f"{cid}: tooltip text {key!r} is already used by {tooltip_owner[key]}")

    errors += cycles(concepts)

    # The spec field quotes the glossary word for word, and every glossary
    # term belongs to exactly one concept.
    glossary = glossary_definitions()
    claimed = Counter(" ".join(c["spec"].split()) for c in concepts if c.get("spec"))
    known = set(glossary.values())
    for c in concepts:
        if c.get("spec") and " ".join(c["spec"].split()) not in known:
            errors.append(f"{c['id']}.spec: does not match any definition in {GLOSSARY} (copy the new wording)")
    for term, definition in glossary.items():
        if claimed[definition] != 1:
            errors.append(f"glossary term {term!r} must be quoted by exactly one concept's spec field")

    seen_pages = set()
    for group in data.get("review_groups", []):
        name = group.get("name", "?")
        for page in group.get("pages", []):
            check_page(f"review group {name}", page)
            if page in seen_pages:
                errors.append(f"review group {name}: {page} is already in another group")
            seen_pages.add(page)
        if len({posixpath.dirname(page) for page in group.get("pages", [])}) != 1:
            errors.append(f"review group {name}: all pages must share one directory")
    return errors


def cycles(concepts):
    """Report requires-cycles (only possible between concepts on the same page)."""
    by_id = {c["id"]: c for c in concepts}
    state, errors = {}, []

    def visit(cid, trail):
        if state.get(cid) == "done" or cid not in by_id:
            return
        if state.get(cid) == "open":
            errors.append("requires cycle: " + " -> ".join(trail[trail.index(cid):] + [cid]))
            return
        state[cid] = "open"
        for rid in by_id[cid]["requires"]:
            visit(rid, trail + [cid])
        state[cid] = "done"

    for cid in by_id:
        visit(cid, [])
    return errors


# ---- rendering ----------------------------------------------------------------


class Memory:
    def __init__(self, data, nav):
        self.concepts = data["concepts"]
        self.groups = data["review_groups"]
        self.nav = nav
        self.pages = {page["path"]: page for page in nav}
        self.order = {page["path"]: i for i, page in enumerate(nav)}
        self.by_id = {c["id"]: c for c in self.concepts}

    def introduced_on(self, page):
        return [c for c in self.concepts if c["introduced_in"] == page]

    def label(self, target, host):
        """Link text: the nav title, prefixed with its section when that differs from the host's."""
        page = self.pages[target]
        if not page["section"] or page["section"] == self.pages[host]["section"]:
            return page["title"]
        return f"{page['section']}: {page['title']}"

    def question(self, concept, host, indent):
        """A collapsed question whose body holds the answer and where to relearn it."""
        pad = " " * indent
        source = concept["introduced_in"]
        where = f"Introduced in [{self.label(source, host)}]({relative_link(source, host)})."
        spec = concept.get("spec_ref")
        if spec and spec.partition("#")[0] != source:
            where += f" Specification: [{self.pages[spec.partition('#')[0]]['title']}]({relative_link(spec, host)})."
        return [
            f'{pad}??? question "{concept["recall_question"]}"',
            "",
            f"{pad}    {concept['recall_answer']}",
            "",
            f"{pad}    {where}",
            "",
        ]

    def remember(self, page):
        here = {c["id"] for c in self.introduced_on(page)}
        # Walk down `requires` from this page's concepts: distance 1 means a
        # direct prerequisite. Closest first, then the most needed, then the
        # most recently introduced.
        distance, need, frontier, step = {}, Counter(), sorted(here), 0
        while frontier:
            step += 1
            following = []
            for cid in frontier:
                for rid in self.by_id[cid]["requires"]:
                    if rid in here:
                        continue
                    if step == 1:
                        need[rid] += 1
                    if rid not in distance:
                        distance[rid] = step
                        following.append(rid)
            frontier = following
        ranked = sorted(
            distance,
            key=lambda rid: (distance[rid], -need[rid], -self.order[self.by_id[rid]["introduced_in"]], rid),
        )
        direct = [rid for rid in ranked if distance[rid] == 1]
        chosen = direct[:REMEMBER_MAX] if len(direct) >= REMEMBER_MIN else ranked[:REMEMBER_MIN]
        if not chosen:
            return ""
        lines = [f"<!-- {NOTICE} -->", "", '???+ remember "Before you start, remember"', ""]
        for rid in chosen:
            lines += self.question(self.by_id[rid], page, indent=4)
        return "\n".join(lines).rstrip() + "\n"

    def next_pages(self, page):
        users = {}
        for c in self.introduced_on(page):
            for later in c["used_in"]:
                users.setdefault(later, []).append(c["term"])
        graph = self.local_map(page)
        if not users and not graph:
            return ""
        lines = [f"<!-- {NOTICE} -->", ""]
        if users:
            best = sorted(users, key=lambda p: (-len(users[p]), self.order[p]))[:NEXT_MAX]
            lines += ['!!! next "You will use this again in"', ""]
            for later in sorted(best, key=self.order.get):
                terms = [f"*{term}*" for term in users[later]]
                shown = ", ".join(terms[:NEXT_TERMS])
                if len(terms) > NEXT_TERMS:
                    shown += f" and {len(terms) - NEXT_TERMS} more"
                lines.append(f"    - [{self.label(later, page)}]({relative_link(later, page)}): {shown}")
            lines.append("")
        if graph:
            lines += ['??? info "Concept map for this page"', "", "    ```mermaid"]
            lines += [f"    {line}" for line in graph.splitlines()]
            lines += ["    ```", ""]
        return "\n".join(lines).rstrip() + "\n"

    def review(self, index):
        group = self.groups[index]
        pages = group["pages"]
        current = [c for c in self.concepts if c["introduced_in"] in pages]
        earlier_pages = {page for g in self.groups[:index] for page in g["pages"]}
        earlier = [c for c in self.concepts if c["introduced_in"] in earlier_pages]
        # Spacing: bring back the earlier concepts this group relies on most.
        earlier.sort(key=lambda c: (-sum(p in pages for p in c["used_in"]), -self.order[c["introduced_in"]], c["id"]))
        picked = current + earlier[: max(5, math.ceil(len(current) / 3))]
        # Interleaving: a fixed pseudo-random order, stable across runs.
        picked.sort(key=lambda c: hashlib.sha1(f"{group['name']}:{c['id']}".encode()).hexdigest())
        lines = [f"<!-- {NOTICE} -->", ""]
        for c in picked:
            lines += self.question(c, pages[0], indent=0)
        return "\n".join(lines).rstrip() + "\n"

    def book(self, concept):
        page = concept["introduced_in"]
        return next((book for prefix, book in BOOKS.items() if page.startswith(prefix)), "other")

    def maps(self):
        def edges(cs):
            return [f"  {mermaid_id(rid)} --> {mermaid_id(c['id'])}" for c in cs for rid in c["requires"]]

        ordered = sorted(self.concepts, key=lambda c: self.order[c["introduced_in"]])
        books = {}
        for c in ordered:
            books.setdefault(self.book(c), []).append(c)
        head = [f"%% {NOTICE}", "flowchart LR"]

        whole = list(head)
        for book, cs in books.items():
            whole += [f'  subgraph book_{book}["{BOOK_TITLES[book]}"]', *(f"    {mermaid_node(c)}" for c in cs), "  end"]
        maps = {"concept-map.mmd": "\n".join(whole + edges(ordered)) + "\n"}

        for book, cs in books.items():
            lines = list(head)
            for page in dict.fromkeys(c["introduced_in"] for c in cs):
                members = [f"    {mermaid_node(c)}" for c in cs if c["introduced_in"] == page]
                lines += [f'  subgraph {mermaid_id(page_key(page), "p_")}["{self.pages[page]["title"]}"]', *members, "  end"]
            outside = {rid for c in cs for rid in c["requires"] if self.book(self.by_id[rid]) != book}
            if outside:
                earlier = sorted(outside, key=lambda rid: (self.order[self.by_id[rid]["introduced_in"]], rid))
                lines += ['  subgraph earlier["From other books"]', *(f"    {mermaid_node(self.by_id[rid])}" for rid in earlier), "  end"]
            maps[f"concept-map-{book}.mmd"] = "\n".join(lines + edges(cs)) + "\n"
        return maps

    def local_map(self, page):
        """Mermaid flowchart of one page's requires-graph neighbourhood: the
        concepts it introduces, what those need first, and what later needs
        them. Same node rendering as maps(), for the "Concept map for this
        page" box at the end of next/<page-key>.md.

        Capped at LOCAL_MAP_MAX nodes: every concept the page introduces is
        kept (dropping one would misrepresent what the page teaches), and
        prerequisites and dependents share whatever budget is left, closest
        (by nav order) first. Edges are only drawn between shown nodes, so a
        trimmed neighbour never leaves a dangling reference.
        """
        here = self.introduced_on(page)
        if not here:
            return ""
        here_ids = {c["id"] for c in here}

        def by_distance(ids):
            return sorted(ids, key=lambda cid: (self.order[self.by_id[cid]["introduced_in"]], cid))

        before = by_distance({rid for c in here for rid in c["requires"]} - here_ids)
        after = by_distance(
            o["id"] for o in self.concepts if o["id"] not in here_ids and not here_ids.isdisjoint(o["requires"])
        )
        budget = max(LOCAL_MAP_MAX - len(here_ids), 0)
        before = before[:budget]
        after = after[: max(budget - len(before), 0)]
        shown = here + [self.by_id[cid] for cid in before + after]
        shown_ids = here_ids.union(before, after)
        lines = ["flowchart LR"]
        lines += [f"  {mermaid_node(c)}" for c in shown]
        lines += [
            f"  {mermaid_id(rid)} --> {mermaid_id(c['id'])}" for c in shown for rid in c["requires"] if rid in shown_ids
        ]
        return "\n".join(lines) + "\n"

    def abbreviations(self):
        keys = {}
        for c in self.concepts:
            keys.update(tooltip_keys(c))
        lines = [f"<!-- {NOTICE} -->", ""]
        lines += [f"*[{key}]: {keys[key]}" for key in sorted(keys, key=lambda k: (k.lower(), k))]
        return "\n".join(lines) + "\n"

    def outputs(self):
        """Every generated file, as {path relative to includes/: text}."""
        out = {"abbreviations.md": self.abbreviations()}
        for page in self.nav:
            key = page_key(page["path"])
            out[f"remember/{key}.md"] = self.remember(page["path"])
            out[f"next/{key}.md"] = self.next_pages(page["path"])
        for index, group in enumerate(self.groups):
            out[f"review/{group['name']}.md"] = self.review(index)
        out.update(self.maps())
        return out

    # ---- used_in suggestions --------------------------------------------------

    def scan(self):
        """Suggest used_in: the later nav pages whose prose mentions the concept most."""
        texts = {page["path"]: prose((DOCS / page["path"]).read_text(encoding="utf-8")) for page in self.nav}
        found = {}
        for c in self.concepts:
            patterns = scan_patterns(c)
            # A distinctive multi-word term or abbreviation counts from one
            # mention; a single common word needs two.
            enough = 1 if c.get("abbr") or len(re.sub(r"\s*\(.*?\)", "", c["term"]).split()) > 1 else 2
            hits = []
            for page in self.nav[self.order[c["introduced_in"]] + 1 :]:
                if page["path"] in NOT_USERS:
                    continue
                count = sum(len(p.findall(texts[page["path"]])) for p in patterns)
                if count >= enough:
                    hits.append((count, page["path"]))
            best = sorted(hits, key=lambda hit: (-hit[0], self.order[hit[1]]))[:USED_IN_MAX]
            found[c["id"]] = sorted((page for _, page in best), key=self.order.get)
        return found


def mermaid_id(text, prefix="c_"):
    return prefix + re.sub(r"\W", "_", text)


def mermaid_node(c):
    return f'{mermaid_id(c["id"])}["{c["term"]}"]'


def prose(text):
    """Page text without code, link targets and URLs, for counting term mentions."""
    text = strip_fences(text)
    text = re.sub(r"`[^`\n]*`", "", text)
    text = re.sub(r"\]\([^)]*\)", "]", text)
    return re.sub(r"<https?://[^>]*>", "", text)


def scan_patterns(concept):
    names = [re.sub(r"\s*\(.*?\)", "", concept["term"]), *concept["aliases"]]
    patterns = []
    for name in names:
        words = [re.escape(word) for word in re.split(r"[\s-]+", name) if word]
        patterns.append(re.compile(r"(?<![\w-])" + r"[\s-]+".join(words) + r"(?:s|es)?(?![\w-])", re.I))
    if concept.get("abbr"):
        patterns.append(re.compile(r"(?<![\w-])" + re.escape(concept["abbr"]) + r"s?(?![\w-])"))
    return patterns


# ---- writing ------------------------------------------------------------------


def sync(outputs, check):
    """Write outputs (or, with check, only compare). Return the stale paths."""
    expected = {OUT / rel: text for rel, text in outputs.items()}
    owned = {OUT / "abbreviations.md", *OUT.glob("concept-map*.mmd")}
    for folder in ("remember", "next", "review"):
        owned.update((OUT / folder).glob("*.md"))
    stale = []
    for path in sorted(owned - expected.keys()):
        stale.append(f"remove {path.relative_to(ROOT)}")
        if not check:
            path.unlink()
    for path, text in sorted(expected.items()):
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            stale.append(f"write  {path.relative_to(ROOT)}")
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    return stale


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    mode.add_argument("--scan", action="store_true", help="print used_in lists suggested by the docs text")
    mode.add_argument("--self-test", action="store_true", help="run the built-in checks")
    args = parser.parse_args([] if argv is None else argv)
    if args.self_test:
        self_test()
        print("concepts.py self-test passed")
        return 0

    nav, data = load_nav(), load_data()
    errors = validate(data, nav)
    if errors:
        print(f"{DATA.relative_to(ROOT)} has {len(errors)} problem(s):", file=sys.stderr)
        print("\n".join(f"  {error}" for error in errors), file=sys.stderr)
        return 2
    memory = Memory(data, nav)

    if args.scan:
        for cid, pages in memory.scan().items():
            if pages != memory.by_id[cid]["used_in"]:
                print(f"{cid}:\n  stored:    {memory.by_id[cid]['used_in']}\n  suggested: {pages}")
        return 0

    stale = sync(memory.outputs(), check=args.check)
    if args.check:
        if stale:
            print("Concept outputs are stale; run python tools/docs/concepts.py", file=sys.stderr)
            print("\n".join(f"  {line}" for line in stale), file=sys.stderr)
            return 1
        print("concept outputs are up to date")
        return 0
    print(f"concepts: {len(memory.concepts)} concepts, {len(stale)} file(s) updated")
    return 0


# ---- self-test ----------------------------------------------------------------


def self_test():
    # Relative links, as seen from the page that includes the snippet.
    stage3 = "compiler/guide/stage-3-parser-and-tree.md"
    assert relative_link("compiler/guide/stage-2-lexer.md", stage3) == "stage-2-lexer.md"
    assert relative_link("language-tour/08-expressions.md", stage3) == "../../language-tour/08-expressions.md"
    assert relative_link("specification/conformance.md#14-x", stage3) == "../../specification/conformance.md#14-x"
    assert relative_link("index.md", stage3) == "../../index.md"
    assert relative_link("compiler/guide/index.md", "index.md") == "compiler/guide/index.md"
    assert relative_link("language-tour/README.md", "language-tour/04-variables-and-types.md") == "README.md"
    assert page_key(stage3) == "compiler__guide__stage-3-parser-and-tree"
    assert slugify("1.4 Static and dynamic rules", "-") == "14-static-and-dynamic-rules"

    # Tooltip filter: abbreviations and multi-word terms only, never one plain word.
    def concept(**fields):
        return {"aliases": [], "short": "Tip.", **fields}

    assert tooltip_keys(concept(term="type")) == {}
    assert tooltip_keys(concept(term="type", tooltip=True)) == {}  # validate() reports this
    assert tooltip_keys(concept(term="basic block")) == {}  # multi-word terms opt in
    keys = tooltip_keys(concept(term="abstract syntax tree", abbr="AST", aliases=["syntax diagram", "tree"]))
    assert keys == {"AST": "abstract syntax tree: Tip.", "abstract syntax tree": "Tip.", "syntax diagram": "Tip."}
    assert tooltip_keys(concept(term="UTF-8", abbr="UTF-8")) == {"UTF-8": "Tip."}
    assert tooltip_keys(concept(term="Pratt parsing", tooltip=True)) == {"Pratt parsing": "Tip."}
    assert tooltip_keys(concept(term="IEEE 754", abbr="IEEE 754", tooltip=False)) == {}
    assert tooltip_keys(concept(term="token", aliases=["lexeme"], abbr="TOK")) == {"TOK": "token: Tip."}

    # Scanning ignores code and link targets, and accepts plurals and hyphen/space variants.
    text = prose("A basic-block ends.\n```\nbasic block\n```\n[x](basic-block.md) and `basic block`. Basic blocks!")
    assert sum(len(p.findall(text)) for p in scan_patterns(concept(term="basic block"))) == 2

    # Local concept map: this page's concepts, their direct prerequisites and
    # direct dependents, with edges only between nodes actually shown.
    def linked(cid, term, page, requires=()):
        return concept(id=cid, term=term, introduced_in=page, requires=list(requires), used_in=[])

    nav = [{"path": p, "title": p, "section": ""} for p in ("n0.md", "n1.md", "n2.md", "n3.md")]
    small = Memory(
        {
            "concepts": [
                linked("a", "A", "n0.md"),
                linked("b", "B", "n1.md", ["a"]),
                linked("c", "C", "n1.md", ["a"]),
                linked("d", "D", "n2.md", ["b"]),
                linked("e", "E", "n3.md"),
            ],
            "review_groups": [],
        },
        nav,
    )
    assert small.local_map("nowhere.md") == ""  # introduces nothing
    assert small.local_map("n3.md") == 'flowchart LR\n  c_e["E"]\n'  # no requires, nothing depends on it
    assert (
        small.local_map("n1.md")
        == "\n".join(
            [
                "flowchart LR",
                '  c_b["B"]',
                '  c_c["C"]',
                '  c_a["A"]',
                '  c_d["D"]',
                "  c_a --> c_b",
                "  c_a --> c_c",
                "  c_b --> c_d",
            ]
        )
        + "\n"
    )
    # A page with neither a "next" list nor a graph stays empty; one with
    # only a graph still gets the collapsed box, indented under it.
    assert small.next_pages("nowhere.md") == ""
    assert small.next_pages("n3.md") == (
        f"<!-- {NOTICE} -->\n\n"
        '??? info "Concept map for this page"\n\n'
        "    ```mermaid\n"
        "    flowchart LR\n"
        '      c_e["E"]\n'
        "    ```\n"
    )

    # The cap: every concept a page introduces is kept even past it, but
    # prerequisites and dependents split whatever budget is left.
    pages = [{"path": p, "title": p, "section": ""} for p in ("p0.md", "p1.md", "big.md")]
    hub = [linked("r", "Root", "p0.md")] + [linked(f"dep{i}", f"D{i}", "p1.md", ["r"]) for i in range(20)]
    assert Memory({"concepts": hub, "review_groups": []}, pages).local_map("p0.md").count("[") == LOCAL_MAP_MAX
    overflow = [linked(f"h{i}", f"H{i}", "big.md") for i in range(LOCAL_MAP_MAX + 3)]
    over_map = Memory({"concepts": overflow, "review_groups": []}, pages).local_map("big.md")
    assert over_map.count("[") == LOCAL_MAP_MAX + 3


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
