"""Write one include file per example, so a page shows an example in one line:

    --8<-- "includes/examples/optimize/p7-loop-transformations/interchange.cpp.md"

The include holds the code block (itself a snippet of the example file, so the
page shows the code that CI compiled), the expected output when there is one,
the references the example follows, and its Compiler Explorer link from
examples/manifest.json.

    python tools/docs/example_links.py           # regenerate
    python tools/docs/example_links.py --check   # exit 1 if anything is stale
"""

import html
import json
import sys
import tomllib
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[2]
EXAMPLES = ROOT / "examples"
OUT = ROOT / "includes" / "examples"
# Example extension -> Pygments lexer for the fence.
LEXER = {".cpp": "cpp", ".s": "gas", ".ll": "llvm", ".mlir": "mlir", ".cu": "cuda", ".metal": "cpp"}


def short(url):
    """'https://www.example.com/a/b/' -> 'example.com/a/b'."""
    parts = urlsplit(url)
    return (parts.netloc.removeprefix("www.") + parts.path).rstrip("/")


def render(path, manifest):
    rel = path.relative_to(ROOT).as_posix()
    out = [f'```{LEXER[path.suffix]} title="{rel}"', f'--8<-- "{rel}"', "```", ""]
    expected = path.with_suffix(".expected")
    if expected.exists():
        out += ['??? example "Output"', "", "    ```text",
                f'    --8<-- "{expected.relative_to(ROOT).as_posix()}"', "    ```", ""]
    meta = path.with_suffix(".toml")
    follows = tomllib.loads(meta.read_text()).get("follows", []) if meta.exists() else []
    links = [f'<a href="{html.escape(u)}">{html.escape(short(u))}</a>' for u in follows]
    parts = ["Follows: " + ", ".join(links) + "."] if links else []
    if rel in manifest:
        parts.append(f'<a class="vx-ce-link" href="{html.escape(manifest[rel]["url"])}">Open in Compiler Explorer</a>')
    if parts:
        out += ['<p class="vx-example-links">' + " ".join(parts) + "</p>", ""]
    return "<!-- Generated by tools/docs/example_links.py; do not edit. -->\n\n" + "\n".join(out)


def main(argv=()):
    check = "--check" in argv
    manifest = json.loads((EXAMPLES / "manifest.json").read_text())
    wanted = {}
    for path in sorted(EXAMPLES.rglob("*")):
        if path.suffix in LEXER:
            rel = path.relative_to(EXAMPLES).as_posix()
            wanted[OUT / f"{rel}.md"] = render(path, manifest)
    stale = [p for p, text in wanted.items() if not p.exists() or p.read_text() != text]
    extra = [p for p in OUT.rglob("*.md") if p not in wanted] if OUT.exists() else []
    if check:
        for p in stale + extra:
            print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale or extra else 0
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(wanted[p])
    for p in extra:
        p.unlink()
    print(f"example_links: {len(wanted)} includes, {len(stale)} written, {len(extra)} removed", file=sys.stderr)
    return 0


if __name__ == "__main__":
    assert short("https://www.example.com/a/b/") == "example.com/a/b"
    sys.exit(main(sys.argv[1:]))
