#!/usr/bin/env python3
r"""Generate railroad (syntax) diagrams from the Vortex EBNF grammar.

Reads every ```ebnf fence in docs/specification/grammar.md and writes, per rule:

    docs/assets/railroad/<rule>.svg   standalone SVG
    includes/railroad/<rule>.md       the same SVG inline, for pymdownx.snippets:
                                      --8<-- "includes/railroad/<rule>.md"

Nonterminals link to HREF; the grammar page must define those anchors. The SVG
has no <style> and no colors: site CSS styles the railroad-diagrams classes
(svg.railroad-diagram, g.terminal, g.non-terminal, path, rect, text).

Accepted EBNF: `rule ::= body ;` with "," sequence, "|" choice, [ ] optional,
{ } zero or more, ( ) grouping, "x" or 'x' terminals (escapes \\ \" \' only)
and (* comments *). Anything else is an error that names its line.

    python tools/docs/railroad.py           regenerate; print grammar lint
    python tools/docs/railroad.py --check   exit 1 if generated files are stale
"""

import argparse
import importlib.machinery
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GRAMMAR = ROOT / "docs" / "specification" / "grammar.md"
SVG_DIR = ROOT / "docs" / "assets" / "railroad"
SNIPPET_DIR = ROOT / "includes" / "railroad"
HREF = "#rule-{}"  # where a nonterminal links to; formatted with the rule name
MARKER = "<!-- Generated by tools/docs/railroad.py from docs/specification/grammar.md. Do not edit. -->"


def _import_railroad():
    """Import the railroad-diagrams package. This script is also named
    railroad.py, so a plain `import railroad` can find the script itself."""
    here = Path(__file__).resolve().parent
    path = [entry for entry in sys.path if Path(entry or ".").resolve() != here]
    spec = importlib.machinery.PathFinder.find_spec("railroad", path)
    if spec is None:
        raise SystemExit("error: railroad.py needs railroad-diagrams==3.0.1 (pip install it)")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


rr = _import_railroad()

# One ```ebnf fence; it may be indented (inside a content tab or admonition).
FENCE = re.compile(r"^(?P<indent>[ \t]*)```[ \t]*ebnf\b[^\n]*\n(?P<body>.*?)^(?P=indent)```[ \t]*$", re.M | re.S)
TOKEN = re.compile(
    r"""(?P<skip>\s+|\(\*.*?\*\))                             # whitespace, (* comment *)
      | (?P<name>[A-Za-z_][A-Za-z0-9_]*)
      | (?P<string>"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*')
      | (?P<op>::=|[,|;()\[\]{}])""",
    re.X | re.S,
)


class GrammarError(Exception):
    """A malformed grammar. The message starts with "<line>: "."""


# Parsed EBNF is nested tuples: (kind, value) where kind is "terminal" or "rule"
# (value: str), "sequence" or "choice" (value: tuple of nodes), "optional" or
# "repeat" (value: one node). Groups ( ) disappear into their contents.


def sequence(nodes):
    return nodes[0] if len(nodes) == 1 else ("sequence", tuple(nodes))


def unquote(token, line):
    """Strip the quotes and decode the grammar's escapes: "\\n" is the text \n."""

    def decode(match):
        if match[1] not in "\\\"'":
            raise GrammarError(f"{line}: unsupported escape \\{match[1]} in {token} (write \\\\ for a backslash)")
        return match[1]

    return re.sub(r"\\(.)", decode, token[1:-1], flags=re.S)


def tokenize(text, line):
    """Split EBNF text into (kind, value, line) tokens; `line` is the first line's number."""
    tokens, pos = [], 0
    while pos < len(text):
        match = TOKEN.match(text, pos)
        if not match:
            raise GrammarError(f"{line}: unsupported EBNF syntax at {text[pos:pos + 20]!r}")
        if match.lastgroup == "string":
            tokens.append(("string", unquote(match[0], line), line))
        elif match.lastgroup != "skip":
            tokens.append((match.lastgroup, match[0], line))
        line += match[0].count("\n")
        pos = match.end()
    return tokens


def parse(text, line=1):
    """Parse EBNF rules into [(name, body, line)] by recursive descent."""
    tokens, pos = tokenize(text, line), 0

    def at(op):
        return pos < len(tokens) and tokens[pos][:2] == ("op", op)

    def take(expected):
        nonlocal pos
        if pos == len(tokens):
            raise GrammarError(f"{tokens[-1][2]}: expected {expected} before the end of the block")
        pos += 1
        return tokens[pos - 1]

    def expect(kind, value, expected):
        token = take(expected)
        if token[0] != kind or value not in (None, token[1]):
            raise GrammarError(f"{token[2]}: expected {expected}, got {token[1]!r}")
        return token

    def choice():  # sequence { "|" sequence }
        alternatives = [items()]
        while at("|"):
            take("|")
            alternatives.append(items())
        return alternatives[0] if len(alternatives) == 1 else ("choice", tuple(alternatives))

    def items():  # item { "," item }
        nodes = [item()]
        while at(","):
            take(",")
            nodes.append(item())
        return sequence(nodes)

    def item():
        kind, value, where = take("a rule name, terminal or group")
        if kind == "name":
            return ("rule", value)
        if kind == "string":
            return ("terminal", value)
        closer = {"(": ")", "[": "]", "{": "}"}.get(value)
        if closer is None:
            raise GrammarError(f"{where}: expected a rule name, terminal or group, got {value!r}")
        body = choice()
        expect("op", closer, repr(closer))
        return {"(": body, "[": ("optional", body), "{": ("repeat", body)}[value]

    rules = []
    while pos < len(tokens):
        _, name, where = expect("name", None, "a rule name")
        expect("op", "::=", "'::='")
        rules.append((name, choice(), where))
        expect("op", ";", "',', '|' or ';'")
    return rules


def load(path):
    """Parse every ```ebnf fence in the file into {rule name: body}, in source order."""
    text = path.read_text(encoding="utf-8")
    rules = {}
    for fence in FENCE.finditer(text):
        for name, body, line in parse(fence["body"], text.count("\n", 0, fence.start("body")) + 1):
            if name in rules:
                raise GrammarError(f"{line}: rule {name!r} is defined twice")
            rules[name] = body
    if not rules:
        raise GrammarError("1: no ```ebnf fences found")
    return rules


def references(node):
    """Yield the nonterminal names used in a node, in source order."""
    kind, value = node
    if kind == "rule":
        yield value
    elif kind in ("sequence", "choice"):
        for child in value:
            yield from references(child)
    elif kind in ("optional", "repeat"):
        yield from references(value)


def lint(rules):
    """Return ({undefined name: [rules using it]}, [rules no other rule uses]).
    The first rule is the start symbol, so it never counts as unused."""
    users = {}  # name -> {rule using it: None}, a dict as an ordered set
    for name, body in rules.items():
        for ref in references(body):
            if ref != name:
                users.setdefault(ref, {})[name] = None
    undefined = {ref: list(by) for ref, by in users.items() if ref not in rules}
    unused = [name for name in list(rules)[1:] if name not in users]
    return undefined, unused


def diagram_item(node, defined):
    """Convert a parsed node to a railroad-diagrams item."""
    kind, value = node
    if kind == "terminal":
        return rr.Terminal(value)
    if kind == "rule":  # an undefined rule has no anchor to link to
        return rr.NonTerminal(value, href=HREF.format(value) if value in defined else None)
    if kind == "optional":
        return rr.Optional(diagram_item(value, defined))
    if kind == "repeat":
        return rr.ZeroOrMore(diagram_item(value, defined))
    if kind == "choice":
        return rr.Choice(0, *(diagram_item(child, defined) for child in value))
    # A sequence. Draw `x, { sep, x }` as one loop through x with sep on the
    # way back (OneOrMore) instead of drawing x twice.
    drawn, last = [], None  # last: the parsed node behind drawn[-1]
    for child in value:
        if child[0] == "repeat" and last is not None:
            body = child[1][1] if child[1][0] == "sequence" else (child[1],)
            if body[-1] == last:
                separator = diagram_item(sequence(body[:-1]), defined) if len(body) > 1 else None
                drawn[-1], last = rr.OneOrMore(drawn[-1], separator), None
                continue
        drawn.append(diagram_item(child, defined))
        last = child
    return drawn[0] if len(drawn) == 1 else rr.Sequence(*drawn)


def render(name, body, defined):
    """SVG markup for one rule, labelled with its name. No <style>, no colors."""
    diagram = rr.Diagram(rr.Start(label=name), diagram_item(body, defined))
    diagram.attrs.update(
        {
            "xmlns": "http://www.w3.org/2000/svg",
            "xmlns:xlink": "http://www.w3.org/1999/xlink",  # the library writes xlink:href links
            "role": "img",
            "aria-label": f"Syntax diagram for {name}",
        }
    )
    parts = []
    diagram.writeSvg(parts.append)
    # railroad-diagrams 3.0.1 writes a linked label twice inside its <a>; keep one.
    return re.sub(r"(<text[^>]*>[^<]*</text>)\1</a>", r"\1</a>", "".join(parts))


def generate(rules):
    """Map each output path to its content."""
    files = {}
    for name, body in rules.items():
        svg = render(name, body, rules)
        files[SVG_DIR / f"{name}.svg"] = f"{MARKER}\n{svg}\n"
        # A <div> makes Python-Markdown pass the SVG through as a raw HTML block.
        files[SNIPPET_DIR / f"{name}.md"] = f'{MARKER}\n<div class="railroad">\n{svg}\n</div>\n'
    return files


def main(argv=()):
    """Regenerate the diagrams (or only check them). Returns an exit status."""
    parser = argparse.ArgumentParser(prog="railroad.py", description="Generate railroad diagrams from the grammar.")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 if generated files are stale")
    args = parser.parse_args(argv)
    source = GRAMMAR.relative_to(ROOT)
    try:
        rules = load(GRAMMAR)
    except GrammarError as error:
        print(f"error: {source}:{error}", file=sys.stderr)
        return 2
    undefined, unused = lint(rules)
    for ref, by in undefined.items():
        print(f"warning: {source}: undefined nonterminal {ref!r} (used by {', '.join(by)}); drawn without a link", file=sys.stderr)
    for name in unused:
        print(f"warning: {source}: rule {name!r} is never referenced", file=sys.stderr)

    files = generate(rules)
    stale = [path for path, text in files.items() if not path.is_file() or path.read_text(encoding="utf-8") != text]
    orphans = sorted({*SVG_DIR.glob("*.svg"), *SNIPPET_DIR.glob("*.md")} - files.keys())
    summary = f"railroad: {len(rules)} rules from {source}, start rule {next(iter(rules))!r}"
    if args.check:
        for path in stale + orphans:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale or orphans:
            print("error: railroad diagrams are out of date; run python tools/docs/railroad.py", file=sys.stderr)
            return 1
        print(f"{summary}; diagrams up to date")
        return 0
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(files[path], encoding="utf-8", newline="\n")
    for path in orphans:
        path.unlink()
    print(f"{summary}; wrote {len(stale)}, removed {len(orphans)} file(s)")
    return 0


def _self_test():
    """Parser, lint and render checks. Runs before every command-line use."""

    def t(text):
        return ("terminal", text)

    def r(name):
        return ("rule", name)

    rules = {name: body for name, body, _ in parse(r'''
        seq    ::= "fn", name, ";" ;
        choice ::= "a" | "b", seq ;
        opt    ::= [ "mut" ] ;
        rep    ::= { "," } ;
        nested ::= ( "(" | [ "[", { "::" | "..=" } ] ), "&&" ;
        quoted ::= "{", "|", '"', "\\", '\'' ;   (* terminals that look like syntax *)
        loop   ::= name, { ",", name } ;
        name   ::= missing ;
    ''')}
    assert rules["seq"] == ("sequence", (t("fn"), r("name"), t(";")))
    assert rules["choice"] == ("choice", (t("a"), ("sequence", (t("b"), r("seq")))))
    assert rules["opt"] == ("optional", t("mut"))
    assert rules["rep"] == ("repeat", t(","))
    inner = ("optional", ("sequence", (t("["), ("repeat", ("choice", (t("::"), t("..=")))))))
    assert rules["nested"] == ("sequence", (("choice", (t("("), inner)), t("&&")))
    assert rules["quoted"] == ("sequence", (t("{"), t("|"), t('"'), t("\\"), t("'")))
    # `missing` has no rule: lint reports it, and main() prints it as a warning.
    assert lint(rules) == ({"missing": ["name"]}, ["choice", "opt", "rep", "nested", "quoted", "loop"])

    svg = render("loop", rules["loop"], rules)
    assert 'xlink:href="#rule-name"' in svg and "<style" not in svg
    assert 'role="img"' in svg and 'aria-label="Syntax diagram for loop"' in svg
    assert svg.count(">name</text>") == 1, "x, { sep, x } should draw x once, as a loop"
    assert "#rule-missing" not in render("name", rules["name"], rules)

    bad = {'x ::= "a"\n  "b" ;': 2, "x ::= ? any ? ;": 1, 'x ::= "\\n" ;': 1, 'x ::= ( "a" ;': 1, "x ::= a": 1}
    for text, line in bad.items():
        try:
            parse(text)
        except GrammarError as error:
            assert str(error).startswith(f"{line}: "), error
        else:
            raise AssertionError(f"accepted bad EBNF {text!r}")


if __name__ == "__main__":
    _self_test()
    sys.exit(main(sys.argv[1:]))
