platforms = ["macos-arm64", "linux-arm64"]
follows = [
  "https://developer.apple.com/documentation/apple-silicon/tuning-your-code-s-performance-for-apple-silicon",
  "https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst",
]
