platforms = ["macos-arm64", "linux-arm64"]
follows = [
  "https://www.airs.com/blog/archives/460",
  "https://github.com/llvm/llvm-project/blob/main/libunwind/include/mach-o/compact_unwind_encoding.h",
]
