flags = ["--one-shot-bufferize=bufferize-function-boundaries function-boundary-type-conversion=identity-layout-map"]
follows = [
  "https://mlir.llvm.org/docs/Bufferization/",
  "https://mlir.llvm.org/docs/Passes/",
]
