follows = [
  "https://en.cppreference.com/cpp/string/byte/isalpha",
  "https://en.cppreference.com/cpp/string/byte/isdigit",
  "https://en.cppreference.com/cpp/string/byte/isspace",
  "https://en.cppreference.com/cpp/string/byte/ispunct",
  "https://en.cppreference.com/cpp/string/basic_string_view",
]
