follows = [
  "https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#occupancy",
  "https://docs.nvidia.com/cuda/cuda-programming-guide/05-appendices/compute-capabilities.html",
  "https://docs.nvidia.com/cuda/hopper-tuning-guide/index.html",
]
