# B1's stack_calc, (7 - 2) * 3, generated by the same one-template-per-node
# rule but for x86-64 System V. Every value still gets its own 4-byte slot
# and eax is the only register the templates touch. Three things changed:
#
#   - a constant is stored straight to its slot (movl $imm, mem), with no
#     trip through a register;
#   - the right operand of sub and imul is read from its slot by the
#     arithmetic instruction itself, so a binary template is three
#     instructions, not four;
#   - the frame is 24 bytes, not 16: call pushed an 8-byte return address,
#     so rsp arrives 8 bytes past a 16-byte boundary, and 8 + 24 = 32 puts
#     it back on one. A leaf does not strictly need that, but a template
#     that later grows a call does.

        .text
        .globl  stack_calc
        .type   stack_calc, @function
        .p2align 4
stack_calc:
        subq    $24, %rsp

        movl    $7, 0(%rsp)         # Const 7 -> slot 0
        movl    $2, 4(%rsp)         # Const 2 -> slot 1

        movl    0(%rsp), %eax       # Sub(slot 0, slot 1) -> slot 2
        subl    4(%rsp), %eax
        movl    %eax, 8(%rsp)

        movl    $3, 12(%rsp)        # Const 3 -> slot 3

        movl    8(%rsp), %eax       # Mul(slot 2, slot 3): the result stays in eax
        imull   12(%rsp), %eax

        addq    $24, %rsp
        ret
        .size   stack_calc, . - stack_calc
