platforms = ["macos-arm64", "linux-arm64"]
follows = [
  "https://developer.arm.com/documentation/102467/0201/Example---matrix-multiplication",
  "https://developer.arm.com/architectures/instruction-sets/intrinsics/",
  "https://clang.llvm.org/docs/LanguageExtensions.html#extensions-to-specify-floating-point-flags",
]
