flags = ["-passes=instcombine"]
follows = [
  "https://llvm.org/docs/LangRef.html#add-instruction",
  "https://llvm.org/docs/LangRef.html#poison-values",
  "https://llvm.org/docs/LangRef.html#fast-math-flags",
]
